src/objects/Account_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Orgs</relationshipLabel>
        <relationshipName>rel_org_to_contact_contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Account__c</fullName>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Contacts</relationshipLabel>
        <relationshipName>rel_org_to_contact_organization</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>How the contact is related to the account.</description>
        <inlineHelpText>How the contact is related to the account.</inlineHelpText>
        <label>Relationship</label>
        <picklist>
            <picklistValues>
                <fullName>Advisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Founder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Org to Contact Relationship</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Relationship Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org to Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ONEN_EXT_JobChangeWizard.cls
public class ONEN_EXT_JobChangeWizard {
// Written by Dave Manelski, copyright (c) 2008 ONE/Northwest
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

	id OldAccountId;
	
	Contact contact = new Contact();
	
	Account_Relationship__c relationship = new Account_Relationship__c (); 

    public ONEN_EXT_JobChangeWizard(ApexPages.StandardController controller) {
        this.contact = (Contact)controller.getRecord();
    	//capture the AccountId for the contact before it changes via the form
        OldAccountId = this.contact.AccountId;
        contact.AccountId = null;
	}

	//getter for the relationship object for the form
    public Account_Relationship__c  getRelationship() {
        if(relationship == null) relationship = new Account_Relationship__c ();
        return relationship;
    } 
    //getter for the contact
    public Contact getContact() {         
        if(contact == null) contact = new Contact();        
        return contact;
    }
    //save action
    public PageReference save() {
        try {
         	update contact;
         
	    } catch (DmlException e) {
            ApexPages.addMessages(e);   
            return null;         	         
	    }
          
        //if they aren't coming from the Individual Account, create the relationship
        if(OldAccountId <> ONEN_DefaultAccount.GetIndividualAccountId()) { 
	        relationship.Related_Account__c = OldAccountId;
	        relationship.Contact__c = contact.id;
	        relationship.Relationship__c = 'Employee';
	        
	        try {
     			insert relationship;
     
    		} catch (DmlException e) {
	            ApexPages.addMessages(e);   
	            return null;         	                  
    		}
	        
	        
        }
           
        PageReference p = new PageReference('/' + contact.id);
        //refresh page
        p.setRedirect(true);
        return p;
    }

}