src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Campaign_Sub_Type__c</fullName>
        <inlineHelpText>Specific campaign categories associated with general campaign types</inlineHelpText>
        <label>Campaign Sub-Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email to Official</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundraiser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday Appeal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Official</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lobby Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting with Official</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phoned Official</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Appeal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tabling</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>For every outreach campaign EXCEPT automated email drip campaigns</description>
        <label>Campaign</label>
    </recordTypes>
</CustomObject>

src/objects/ONEN_DefaultCampaignStatusSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Campaign_Statuses_1__c</fullName>
        <inlineHelpText>Enter each status on a separate line.  On each line, enter the status name, then y/n is it a Responded status, then y/n is it the default.  Separate each by semicolons.  Use &quot;y&quot; or &quot;n&quot; for the y/n values.  Example: &quot;Attended;y;n&quot; (without the quotes)</inlineHelpText>
        <label>Campaign Statuses 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Statuses_2__c</fullName>
        <inlineHelpText>Enter each status on a separate line. On each line, enter the status name, then y/n is it a Responded status, then y/n is it the default. Separate each by semicolons. Use &quot;y&quot; or &quot;n&quot; for the y/n values. Example: &quot;Attended;y;n&quot; (without the quotes)</inlineHelpText>
        <label>Campaign Statuses 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Statuses_3__c</fullName>
        <inlineHelpText>Enter each status on a separate line. On each line, enter the status name, then y/n is it a Responded status, then y/n is it the default. Separate each by semicolons. Use &quot;y&quot; or &quot;n&quot; for the y/n values. Example: &quot;Attended;y;n&quot; (without the quotes)</inlineHelpText>
        <label>Campaign Statuses 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Statuses_4__c</fullName>
        <inlineHelpText>Enter each status on a separate line. On each line, enter the status name, then y/n is it a Responded status, then y/n is it the default. Separate each by semicolons. Use &quot;y&quot; or &quot;n&quot; for the y/n values. Example: &quot;Attended;y;n&quot; (without the quotes)</inlineHelpText>
        <label>Campaign Statuses 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Statuses_5__c</fullName>
        <inlineHelpText>Enter each status on a separate line. On each line, enter the status name, then y/n is it a Responded status, then y/n is it the default. Separate each by semicolons. Use &quot;y&quot; or &quot;n&quot; for the y/n values. Example: &quot;Attended;y;n&quot; (without the quotes)</inlineHelpText>
        <label>Campaign Statuses 5</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Type_Subtype_1__c</fullName>
        <inlineHelpText>Enter a type and/or type+subtype as text, separated by a semicolon (ex: &quot;Event;House Party&quot;, without the quotes).   Even if you are omitting the subtype, still include the semicolon at the end of your string.</inlineHelpText>
        <label>Campaign Type/Subtype 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Type_Subtype_2__c</fullName>
        <inlineHelpText>Enter a type and/or type+subtype as text, separated by a semicolon (ex: &quot;Event;House Party&quot;, without the quotes). Even if you are omitting the subtype, still include the semicolon at the end of your string.</inlineHelpText>
        <label>Campaign Type/Subtype 2</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Type_Subtype_3__c</fullName>
        <inlineHelpText>Enter a type and/or type+subtype as text, separated by a semicolon (ex: &quot;Event;House Party&quot;, without the quotes). Even if you are omitting the subtype, still include the semicolon at the end of your string.</inlineHelpText>
        <label>Campaign Type/Subtype 3</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Type_Subtype_4__c</fullName>
        <inlineHelpText>Enter a type and/or type+subtype as text, separated by a semicolon (ex: &quot;Event;House Party&quot;, without the quotes). Even if you are omitting the subtype, still include the semicolon at the end of your string.</inlineHelpText>
        <label>Campaign Type/Subtype 4</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Type_Subtype_5__c</fullName>
        <inlineHelpText>Enter a type and/or type+subtype as text, separated by a semicolon (ex: &quot;Event;House Party&quot;, without the quotes). Even if you are omitting the subtype, still include the semicolon at the end of your string.</inlineHelpText>
        <label>Campaign Type/Subtype 5</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Default Campaign Status Settings</label>
</CustomObject>

src/classes/ONEN_TEST_CampaignSetMemberStatuses.cls
// Written by David Manelski, copyright (c) 2008 ONE/Northwest
// This program is released under the GNU General Public License. http://www.gnu.org/licenses/


@isTest 
private class ONEN_TEST_CampaignSetMemberStatuses {

/* 
DEPRECATED 12.1.09 MS
These tests moved to the CampaignMemberStatus class

    static void setDefaultSettings() {
        ONEN_DefaultCampaignStatusSettings__c settings = ONEN_DefaultCampaignStatusSettings__c.getOrgDefaults();
        settings.Campaign_Type_Subtype_1__c = 'Communication;Email';
        settings.Campaign_Statuses_1__c = 'Opened;y;n\nClicked;y;n\nUnsubscribed;n;n\nBounced;n;n';
        settings.Campaign_Type_Subtype_2__c = 'Appeal;';
        settings.Campaign_Statuses_2__c = 'Donated;y;n';
        settings.Campaign_Type_Subtype_3__c = 'Event;';
        settings.Campaign_Statuses_3__c = 'Invited;n;y\nAttended;y;n';
        settings.Campaign_Type_Subtype_4__c = null;
        settings.Campaign_Statuses_4__c = null;
        settings.Campaign_Type_Subtype_5__c = null;
        settings.Campaign_Statuses_5__c = null;
        update settings;
    }


    public static testMethod void testEmailStatuses() {
        
        setDefaultSettings();
        
        //create a campaign that WON'T trip the trigger to ensure that all of the statuses
        //exist in the CampaignMemberStatus table -- to prevent test errors when statuses don't
        //already exist in production.
        Campaign newCampaign = new Campaign (
            Name = 'Bogus_Campaign'             
        );
        insert newCampaign;
        
        List<CampaignMemberStatus> newStatuses = new List<CampaignMemberStatus>();
        CampaignMemberStatus statusOne = new CampaignMemberStatus(
                Label = 'Opened',
                CampaignId = newCampaign.id,
                HasResponded = true,
                SortOrder = 7
        );
        newStatuses.add(statusOne);     

        CampaignMemberStatus statusTwo = new CampaignMemberStatus(
            Label = 'Clicked',
            CampaignId = newCampaign.id,
            HasResponded = true,
            SortOrder = 8
        );
        newStatuses.add(statusTwo);     

        CampaignMemberStatus statusThree = new CampaignMemberStatus(
            Label = 'Unsubscribed',
            CampaignId = newCampaign.id,
            HasResponded = true,
            SortOrder = 9
        );
        newStatuses.add(statusThree);
        
        CampaignMemberStatus statusFour = new CampaignMemberStatus(
            Label = 'Bounced',
            CampaignId = newCampaign.id,
            HasResponded = true,
            SortOrder = 10
        );
        newStatuses.add(statusFour);
        
        if ( newStatuses.size() > 0 ) {
            insert newStatuses;
        }
        
        // Insert a new campaign with CampaignSub-Type 'Email' to test the trigger
        // TBD these tests should set settings so doesn't rely on user settings
        Campaign newCampaign1 = new Campaign (
            Name = 'New Campaign',
            Campaign_Type__c = 'Communication',
            Campaign_Sub_Type__c = 'Email'              
        );
    
        insert newCampaign1;
    
        // Verify that the new Campaign Member Status 'Opened' has been created
        CampaignMemberStatus newStatusOne = [select CampaignId, Label from CampaignMemberStatus where CampaignId = :newCampaign1.id and Label = 'Opened' limit 1];
        System.assertEquals('Opened', newStatusOne.Label);
        
        // Verify that the new Campaign Member Status 'Clicked' has been created
        CampaignMemberStatus newStatusTwo = [select CampaignId, Label from CampaignMemberStatus where CampaignId = :newCampaign1.id and Label = 'Clicked' limit 1];
        System.assertEquals('Clicked', newStatusTwo.Label);
        
        // Verify that the new Campaign Member Status 'Unsubscribed' has been created
        CampaignMemberStatus newStatusThree = [select CampaignId, Label from CampaignMemberStatus where CampaignId = :newCampaign1.id and Label = 'Unsubscribed' limit 1];
        System.assertEquals('Unsubscribed', newStatusThree.Label);
        
        // Verify that the new Campaign Member Status 'Unsubscribed' has been created
        CampaignMemberStatus newStatusFour = [select CampaignId, Label from CampaignMemberStatus where CampaignId = :newCampaign1.id and Label = 'Bounced' limit 1];
        System.assertEquals('Bounced', newStatusFour.Label);
    }
    
    public static testMethod void testAppealStatuses() {

        setDefaultSettings();
        
        //create a campaign that WON'T trip the trigger to ensure that all of the statuses
        //exist in the CampaignMemberStatus table -- to prevent test errors when statuses don't
        //already exist in production.
        Campaign newCampaign = new Campaign (
            Name = 'Bogus_Campaign'             
        );
        insert newCampaign;
        
        List<CampaignMemberStatus> newStatuses = new List<CampaignMemberStatus>();
        CampaignMemberStatus statusFive = new CampaignMemberStatus(
                Label = 'Donated',
                CampaignId = newCampaign.id,
                HasResponded = true,
                SortOrder = 11
            );
            newStatuses.add(statusFive);
        
        if ( newStatuses.size() > 0 ) {
            insert newStatuses;
        }
        
        // Insert a new campaign with Campaign Type 'Appeal' to test
        Campaign newCampaign2 = new Campaign (
            Name = 'New Campaign',
            Campaign_Type__c = 'Appeal'             
        );
    
        insert newCampaign2;
    
        // Verify that the new Campaign Member Status 'Donated' has been created
        CampaignMemberStatus newStatusFive = [select CampaignId, Label from CampaignMemberStatus where CampaignId = :newCampaign2.id and Label = 'Donated' limit 1];
        System.assertEquals('Donated', newStatusFive.Label);
        
    }
    
    public static testMethod void testEventStatuses() {

        setDefaultSettings();
        
        //create a campaign that WON'T trip the trigger to ensure that all of the statuses
        //exist in the CampaignMemberStatus table -- to prevent test errors when statuses don't
        //already exist in production.
        Campaign newCampaign = new Campaign (
            Name = 'Bogus_Campaign'             
        );
        insert newCampaign;
        
        List<CampaignMemberStatus> newStatuses = new List<CampaignMemberStatus>();
        CampaignMemberStatus statusSix = new CampaignMemberStatus(
                Label = 'Invited',
                CampaignId = newCampaign.id,
                HasResponded = false,
                SortOrder = 12
        );
        newStatuses.add(statusSix);
        
        CampaignMemberStatus statusSeven = new CampaignMemberStatus(
            Label = 'Attended',
            CampaignId = newCampaign.id,
            HasResponded = true,
            SortOrder = 13
        );
        newStatuses.add(statusSeven);
        
        if ( newStatuses.size() > 0 ) {
            insert newStatuses;
        }
        
        // Insert a new campaign with Campaign Type 'Appeal' to test
        Campaign newCampaign3 = new Campaign (
            Name = 'New Campaign',
            Campaign_Type__c = 'Event'              
        );
    
        insert newCampaign3;
    
        // Verify that the new Campaign Member Status 'Invited' has been created
        CampaignMemberStatus newStatusSix = [select CampaignId, Label from CampaignMemberStatus where CampaignId = :newCampaign3.id and Label = 'Invited' limit 1];
        System.assertEquals('Invited', newStatusSix.Label);
        
        // Verify that the new Campaign Member Status 'Attended' has been created
        CampaignMemberStatus newStatusSeven = [select CampaignId, Label from CampaignMemberStatus where CampaignId = :newCampaign3.id and Label = 'Attended' limit 1];
        System.assertEquals('Attended', newStatusSeven.Label);
        
    }
*/  
    
}