src/objects/Payment_Notification__c.object
<CustomObject>
    <fields>
        <fullName>IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Email__c</fullName>
        <label>Payer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Payer_ID__c</fullName>
        <label>Payer ID</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Transaction_Id__c</fullName>
        <label>Recurring Transaction Id</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <label>Transaction Id</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Payment Notification</label>
    <nameField>
        <label>Notification Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GW_SCHED_ProcessAuthNetNotifications.cls
global class GW_SCHED_ProcessAuthNetNotifications implements Schedulable {

	global void execute(SchedulableContext SC) {
		
		string query = 'SELECT id, Transaction_Type__c, Transaction_Id__c, Recurring_Transaction_Id__c, Item_Name__c, Payer_Email__c,' +          
						'Payer_ID__c, Payment_Amount__c, Payment_Status__c' +
						'FROM Payment_Notification__c' +
						'WHERE IsProcessed__c = false' +
						'AND IsTest__c = false';
		GW_BATCH_AuthnetAsyncProcessing aapBatch = new GW_BATCH_AuthnetAsyncProcessing(query);
		id batchinstanceid = database.executeBatch (aapBatch, 10);  
		
	}

}