src/objects/Payment_Notification__c.object
<CustomObject>
    <fields>
        <fullName>IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Test</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <label>Item Number</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameters__c</fullName>
        <label>Parameters</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Transaction_Id__c</fullName>
        <label>Parent Transaction Id</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payer_Email__c</fullName>
        <label>Payer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Payer_ID__c</fullName>
        <label>Payer ID</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Error__c</fullName>
        <inlineHelpText>The apex exception message for a notification that can&apos;t be processed successfully</inlineHelpText>
        <label>Processing Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Transaction_Id__c</fullName>
        <label>Recurring Transaction Id</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Id__c</fullName>
        <label>Transaction Id</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Payment Notification</label>
    <nameField>
        <label>Notification Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GW_BATCH_PaypalAsyncProcessing.cls
// batch apex class to process paypal payment notifications later (via scheduled apex) 
// Written by David Habib, copyright (c) 2011 Groundwire, 1402 3rd Avenue, Suite 1000, Seattle, WA 98101
// This program is released under the GNU Affero General Public License, Version 3. http://www.gnu.org/licenses/

global class GW_BATCH_PaypalAsyncProcessing implements Database.Batchable<SObject>, Schedulable {

	public String query { get; set; }

	// constructors
	public GW_BATCH_PaypalAsyncProcessing() {
		system.debug(LoggingLevel.INFO, 'creating a new PayPal batch class.');
		query = 'SELECT id, Transaction_Type__c, Transaction_Id__c, Recurring_Transaction_Id__c, ' +
				'Parent_Transaction_Id__c, Item_Name__c, Item_Number__c, Payer_Email__c, IsProcessed__c, ' +
         		'Payer_ID__c, Payment_Amount__c, Payment_Status__c, Parameters__c, Processing_Error__c from Payment_Notification__c ' + 
                'WHERE IsProcessed__c = false AND IsTest__c = false AND transaction_type__c != null ' +
                'AND Payment_Status__c != \'Error\' AND Payment_Status__c != \'Declined\' ' +
                'ORDER BY transaction_type__c DESC ';        
	}
	
	public GW_BATCH_PaypalAsyncProcessing(string q) { 
		query = q; 
	}

	global database.Querylocator start(Database.BatchableContext bc) {
		system.debug(LoggingLevel.INFO, 'start call on GW_BATCH_PaypalAsyncProcessing');
		return Database.getQueryLocator(query);		 
	}

	global void execute(SchedulableContext SC) {		
		system.debug(LoggingLevel.INFO, 'schedule an execute on GW_BATCH_PaypalAsyncProcessing');
		GW_BATCH_PaypalAsyncProcessing batch = new GW_BATCH_PaypalAsyncProcessing();		
		id batchinstanceid = database.executeBatch (batch); // keep our batch size small to avoid too many soql's
	}

	global public void execute(Database.BatchableContext bc, Sobject[] result) {
		system.debug(LoggingLevel.INFO, 'execute call on GW_BATCH_PaypalAsyncProcessing');
		for (SObject sobj : result) {
			//system.assertEquals(false, sobj.get('IsProcessed__c'));
			GW_CTRL_PaypalNotification.ProcessIPN((Payment_Notification__c)sobj, false);
			//system.assertEquals(true, sobj.get('IsProcessed__c')); 
		} 
		
		// update the ipn records
		update result;
	}
	
	global void finish(Database.BatchableContext bc) {
		system.debug(LoggingLevel.INFO, 'finish call on GW_BATCH_PaypalAsyncProcessing');		
		// clear out old notifications
		GW_CTRL_PaypalNotification.deleteOldNotifications();		
	}

// NOTE: No test code, because this class gets full test coverage
// from tests in GW_CTRL_PaypalNotification.cls

}